CREATE DATABASE DB_QLBH;
GO
USE DB_QLBH;
GO

CREATE TABLE Tinh (
    MaTinh SMALLINT PRIMARY KEY,
	TenTinh NVARCHAR(50) NOT NULL
);
GO

CREATE TABLE Xa (
    MaXa SMALLINT PRIMARY KEY,
	TenXa NVARCHAR(50) NOT NULL,
	MaTinh SMALLINT NOT NULL,
	CONSTRAINT FK_Xa_Tinh FOREIGN KEY (MaTinh)
        REFERENCES Tinh(MaTinh) ON DELETE CASCADE
);
GO

CREATE TABLE Nuoc (
    MaNuoc CHAR(5) PRIMARY KEY,
    TenNuoc NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE Hang (
    MaHang CHAR(5) PRIMARY KEY,
    TenHang NVARCHAR(100) NOT NULL,
    MaNuoc CHAR(5) NOT NULL,
    CONSTRAINT FK_Hang_Nuoc FOREIGN KEY (MaNuoc)
        REFERENCES Nuoc(MaNuoc)
);
GO

CREATE TABLE NhaCC (
    MaNCC VARCHAR(10) PRIMARY KEY,
    TenNCC NVARCHAR(100) NOT NULL,
    DienThoaiNCC VARCHAR(15) NOT NULL,
    EmailNCC VARCHAR(100),
    DiaChiNCC NVARCHAR(255) NOT NULL,
	MaXa SMALLINT NOT NULL,
	CONSTRAINT FK_Xa_NhaCC FOREIGN KEY (MaXa)
        REFERENCES Xa(MaXa)
);
GO

CREATE TABLE KhachHang(
    MaKH VARCHAR(10) PRIMARY KEY,
    TenKH NVARCHAR(50) NOT NULL,
    AnhKH NVARCHAR(255),

    DienThoaiKH VARCHAR(15) NOT NULL,
    EmailKH NVARCHAR(255) NOT NULL,
    DiaChiKH NVARCHAR(255) NOT NULL,
	TenDNKH VARCHAR(50),
    MatKhauKH VARCHAR(255),
	MaXa SMALLINT NOT NULL,
	CONSTRAINT FK_Xa_KhachHang FOREIGN KEY (MaXa)
        REFERENCES Xa(MaXa)
);
GO

CREATE TABLE NhanVien (
    MaNV VARCHAR(10) PRIMARY KEY,
    TenNV NVARCHAR(100) NOT NULL,
    VaiTro NVARCHAR(50) NOT NULL 
        CHECK (VaiTro IN (N'Quản Trị', N'Nhân Viên', N'Quản Lý')),
    TenDNNV VARCHAR(50),
    MatKhauNV VARCHAR(255)
);
GO

CREATE TABLE NhomSP (
    MaNhom VARCHAR(10) PRIMARY KEY,
    TenNhom NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE LoaiSP(
    MaLoai VARCHAR(10) PRIMARY KEY,
    TenLoai NVARCHAR(50) NOT NULL,
    MaNhom VARCHAR(10) NOT NULL,
    CONSTRAINT FK_LoaiSP_NhomSP FOREIGN KEY (MaNhom)
        REFERENCES NhomSP(MaNhom)
);
GO

CREATE TABLE SanPham(
    MaSP VARCHAR(10) PRIMARY KEY,
    TenSP NVARCHAR(50) NOT NULL,
    DonGia DECIMAL(18,2) NOT NULL,
    GiaBan DECIMAL(18,2) NOT NULL,

    MoTaSP NVARCHAR(MAX) NOT NULL,
    AnhMH NVARCHAR(255) NOT NULL,
    ThanhPhan NVARCHAR(MAX) NOT NULL,
    CongDung NVARCHAR(MAX) NOT NULL,
    HDSD NVARCHAR(MAX) NOT NULL,
    XuatXu NVARCHAR(MAX) NOT NULL,
    BaoQuan NVARCHAR(MAX) NOT NULL,
    
    TrangThai NVARCHAR(50) NOT NULL 
        CHECK (TrangThai IN (N'Còn Hàng', N'Hết Hàng', N'Cháy Hàng', N'Sắp Hết')),
    SoLuongTon INT NOT NULL,

    MaLoai VARCHAR(10) NOT NULL,
	MaHang CHAR(5) NOT NULL
	CONSTRAINT FK_SanPham_Hang FOREIGN KEY (MaHang)
		REFERENCES Hang(MaHang),
    CONSTRAINT FK_SanPham_LoaiSP FOREIGN KEY (MaLoai)
        REFERENCES LoaiSP(MaLoai)
);
GO

CREATE TABLE DonMuaHang(
    MaDMH CHAR(11) PRIMARY KEY,
    NgayMH DATE NOT NULL,
    MaNCC VARCHAR(10) NOT NULL,
	MaNV VARCHAR(10) NOT NULL,
    CONSTRAINT FK_DonMuaHang_NhaCC FOREIGN KEY (MaNCC)
        REFERENCES NhaCC(MaNCC),
	CONSTRAINT FK_DonMuaHang_NhanVien FOREIGN KEY (MaNV)
    REFERENCES NhanVien(MaNV)
);
GO

CREATE TABLE DonBanHang(
    MaDBH CHAR(11) PRIMARY KEY,
    NgayBH DATE NOT NULL,
    MaKH VARCHAR(10) NOT NULL,
    CONSTRAINT FK_DonBanHang_KhachHang FOREIGN KEY (MaKH)
        REFERENCES KhachHang(MaKH)
);
GO

CREATE TABLE CTMH(
    MaDMH CHAR(11) NOT NULL,
    MaSP VARCHAR(10) NOT NULL,
    SLM INT NOT NULL,
    DGM DECIMAL(18,2) NOT NULL,
    CONSTRAINT PK_CTMH PRIMARY KEY(MaDMH, MaSP),
    CONSTRAINT FK_CTMH_DonMuaHang FOREIGN KEY (MaDMH)
        REFERENCES DonMuaHang(MaDMH) ON DELETE CASCADE,
    CONSTRAINT FK_CTMH_SanPham FOREIGN KEY (MaSP)
        REFERENCES SanPham(MaSP)
);
GO

CREATE TABLE CTBH(
    MaDBH CHAR(11) NOT NULL,
    MaSP VARCHAR(10) NOT NULL,
    SLB INT NOT NULL,
    DGB DECIMAL(18,2) NOT NULL,
    CONSTRAINT PK_CTBH PRIMARY KEY(MaDBH, MaSP),
    CONSTRAINT FK_CTBH_DonBanHang FOREIGN KEY (MaDBH)
        REFERENCES DonBanHang(MaDBH) ON DELETE CASCADE,
    CONSTRAINT FK_CTBH_SanPham FOREIGN KEY (MaSP)
        REFERENCES SanPham(MaSP)
);
GO
